//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class CreateNewBug
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewBug() : base("LightSwitchApplication:CreateNewBug")
        {
            global::LightSwitchApplication.CreateNewBug.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewBug CreateInstance()
        {
            return new global::LightSwitchApplication.CreateNewBug(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewBug_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewBug_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewBug_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewBug_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewBug_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewBug_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewBug_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void BugProperty_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Bug BugProperty
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewBug.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySetProperties.BugProperty);
            }
            set
            {
                global::LightSwitchApplication.CreateNewBug.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySetProperties.BugProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass, global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewBug.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewBug.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySetProperties.BugProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass>.Entry
                __CreateNewBugEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewBug.DetailsClass.__CreateNewBug_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewBug.DetailsClass.__CreateNewBug_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewBug.DetailsClass.__CreateNewBug_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewBug.DetailsClass.__CreateNewBug_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewBug.DetailsClass.__CreateNewBug_InvokeCreated,
                    global::LightSwitchApplication.CreateNewBug.DetailsClass.__CreateNewBug_InvokeActivated,
                    global::LightSwitchApplication.CreateNewBug.DetailsClass.__CreateNewBug_InvokeSaveErrorEvent);
            private static void __CreateNewBug_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewBug s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewBug_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewBug_InvokeSavingEvent(global::LightSwitchApplication.CreateNewBug s)
            {
                bool handled = false;
                s.CreateNewBug_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewBug_InvokeSavedEvent(global::LightSwitchApplication.CreateNewBug s)
            {
                s.CreateNewBug_Saved();
            }
            private static bool __CreateNewBug_InvokeClosingEvent(global::LightSwitchApplication.CreateNewBug s)
            {
                bool cancel = false;
                s.CreateNewBug_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewBug_InvokeCreated(global::LightSwitchApplication.CreateNewBug s)
            {
                s.CreateNewBug_Created();
            }
            private static void __CreateNewBug_InvokeActivated(global::LightSwitchApplication.CreateNewBug s)
            {
                s.CreateNewBug_Activated();
            }
            private static bool __CreateNewBug_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewBug s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewBug_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewBug.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewBug.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass, global::LightSwitchApplication.Bug>.Data _BugProperty;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass, global::LightSwitchApplication.Bug> BugProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass, global::LightSwitchApplication.Bug>)base.GetItem(global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySetProperties.BugProperty);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass, global::LightSwitchApplication.Bug>.Entry
                    BugProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass, global::LightSwitchApplication.Bug>.Entry(
                        "BugProperty",
                        false,
                        global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySetProperties._BugProperty_Stub,
                        global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySetProperties._BugProperty_Validate,
                        global::LightSwitchApplication.CreateNewBug.DetailsClass.PropertySetProperties._BugProperty_OnValueChanged);
                private static void _BugProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewBug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewBug, global::LightSwitchApplication.CreateNewBug.DetailsClass, global::LightSwitchApplication.Bug>.Data> c, global::LightSwitchApplication.CreateNewBug.DetailsClass d, object sf)
                {
                    c(d, ref d._BugProperty, sf);
                }
                private static void _BugProperty_Validate(global::LightSwitchApplication.CreateNewBug s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.BugProperty_Validate(r);
                }
                private static void _BugProperty_OnValueChanged(global::LightSwitchApplication.CreateNewBug s)
                {
                    s.BugProperty_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SearchBugs
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SearchBugs() : base("LightSwitchApplication:SearchBugs")
        {
            global::LightSwitchApplication.SearchBugs.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SearchBugs CreateInstance()
        {
            return new global::LightSwitchApplication.SearchBugs(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBugs_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBugs_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBugs_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBugs_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBugs_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBugs_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBugs_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Bugs_SelectionChanged();

        partial void Bugs_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bugs_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Bugs visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Bug> Bugs
        {
            get
            {
                return global::LightSwitchApplication.SearchBugs.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties.Bugs);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bugs_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the CreateBug screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void CreateBug()
        {
            this.Details.Methods.CreateBug.CreateInvocation().Execute();
        }
        partial void CreateBug_CanExecute(ref bool result);
        partial void CreateBug_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass, global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySet, global::LightSwitchApplication.SearchBugs.DetailsClass.CommandSet, global::LightSwitchApplication.SearchBugs.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties.Bugs;
                var initializeCommandEntry = global::LightSwitchApplication.SearchBugs.DetailsClass.CommandSetProperties.CreateBug;
                var initializeMethodEntry = global::LightSwitchApplication.SearchBugs.DetailsClass.MethodSetProperties.CreateBug;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Entry
                __SearchBugsEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Entry(
                    global::LightSwitchApplication.SearchBugs.DetailsClass.__SearchBugs_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SearchBugs.DetailsClass.__SearchBugs_InvokeSavingEvent,
                    global::LightSwitchApplication.SearchBugs.DetailsClass.__SearchBugs_InvokeSavedEvent,
                    global::LightSwitchApplication.SearchBugs.DetailsClass.__SearchBugs_InvokeClosingEvent,
                    global::LightSwitchApplication.SearchBugs.DetailsClass.__SearchBugs_InvokeCreated,
                    global::LightSwitchApplication.SearchBugs.DetailsClass.__SearchBugs_InvokeActivated,
                    global::LightSwitchApplication.SearchBugs.DetailsClass.__SearchBugs_InvokeSaveErrorEvent);
            private static void __SearchBugs_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SearchBugs s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SearchBugs_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SearchBugs_InvokeSavingEvent(global::LightSwitchApplication.SearchBugs s)
            {
                bool handled = false;
                s.SearchBugs_Saving(ref handled);
                return handled;
            }
            private static void __SearchBugs_InvokeSavedEvent(global::LightSwitchApplication.SearchBugs s)
            {
                s.SearchBugs_Saved();
            }
            private static bool __SearchBugs_InvokeClosingEvent(global::LightSwitchApplication.SearchBugs s)
            {
                bool cancel = false;
                s.SearchBugs_Closing(ref cancel);
                return cancel;
            }
            private static void __SearchBugs_InvokeCreated(global::LightSwitchApplication.SearchBugs s)
            {
                s.SearchBugs_Created();
            }
            private static void __SearchBugs_InvokeActivated(global::LightSwitchApplication.SearchBugs s)
            {
                s.SearchBugs_Activated();
            }
            private static bool __SearchBugs_InvokeSaveErrorEvent(global::LightSwitchApplication.SearchBugs s, global::System.Exception ex)
            {
                bool handled = false;
                s.SearchBugs_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SearchBugs.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SearchBugs.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable BugsQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.OrderByDescending(
                        this.Screen.DataWorkspace.ApplicationData.Bugs,
                        (b) => b.DateLogged),
                    "Tester");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass, global::LightSwitchApplication.Bug>.Data _Bugs;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Data _CreateBugCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Data _CreateBugMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass, global::LightSwitchApplication.Bug> Bugs
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass, global::LightSwitchApplication.Bug>)base.GetItem(global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties.Bugs);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass> CreateBug
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBugs.DetailsClass.CommandSetProperties.CreateBug);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass> CreateBug
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBugs.DetailsClass.MethodSetProperties.CreateBug);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass, global::LightSwitchApplication.Bug>.Entry
                    Bugs = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass, global::LightSwitchApplication.Bug>.Entry(
                        "Bugs",
                        global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties._Bugs_Stub,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties._Bugs_Validate,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties._Bugs_CreateQuery,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties._Bugs_SelectionChanged,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties._Bugs_OnCollectionChanged,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.PropertySetProperties._Bugs_OnLoaded);
                private static void _Bugs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBugs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass, global::LightSwitchApplication.Bug>.Data> c, global::LightSwitchApplication.SearchBugs.DetailsClass d, object sf)
                {
                    c(d, ref d._Bugs, sf);
                }
                private static void _Bugs_Validate(global::LightSwitchApplication.SearchBugs s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Bugs_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Bugs_CreateQuery(global::LightSwitchApplication.SearchBugs.DetailsClass d, object[] args)
                {
                    return d.BugsQuery();
                }
                private static void _Bugs_SelectionChanged(global::LightSwitchApplication.SearchBugs s)
                {
                    s.Bugs_SelectionChanged();
                }
                private static void _Bugs_OnCollectionChanged(global::LightSwitchApplication.SearchBugs s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Bugs_Changed(e);
                }
                private static void _Bugs_OnLoaded(global::LightSwitchApplication.SearchBugs s, bool succeeded)
                {
                    s.Bugs_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Entry
                    CreateBug = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Entry(
                        "CreateBug",
                        global::LightSwitchApplication.SearchBugs.DetailsClass.CommandSetProperties._CreateBug_Stub,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.CommandSetProperties._CreateBug_CreateExecutableObject);
                private static void _CreateBug_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBugs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBugs.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateBugCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _CreateBug_CreateExecutableObject(global::LightSwitchApplication.SearchBugs.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.SearchBugs.DetailsClass)d).Methods.CreateBug.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Entry
                    CreateBug = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Entry(
                        "CreateBug",
                        global::LightSwitchApplication.SearchBugs.DetailsClass.MethodSetProperties._CreateBug_Stub,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.MethodSetProperties._CreateBug_CanInvoke,
                        global::LightSwitchApplication.SearchBugs.DetailsClass.MethodSetProperties._CreateBug_InvokeMethod);
                private static void _CreateBug_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBugs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBugs, global::LightSwitchApplication.SearchBugs.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBugs.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateBugMethod, sf);
                }
                private static global::System.Exception _CreateBug_CanInvoke(global::LightSwitchApplication.SearchBugs.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.CreateBug_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _CreateBug_InvokeMethod(global::LightSwitchApplication.SearchBugs.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.CreateBug_Execute();
                }

            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class BugDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private BugDetail(int BugId) : base("LightSwitchApplication:BugDetail")
        {
                this.BugId = BugId;
            global::LightSwitchApplication.BugDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static BugDetail CreateInstance(int BugId)
        {
            return new global::LightSwitchApplication.BugDetail(
                        BugId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Bug_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bug_Loaded(bool succeeded);

        partial void BugId_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Bug Bug
        {
            get
            {
                return global::LightSwitchApplication.BugDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties.Bug);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bug_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int BugId
        {
            get 
            {
                return global::LightSwitchApplication.BugDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties.BugId);
            }
            set
            {
                global::LightSwitchApplication.BugDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties.BugId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the Delete screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Delete()
        {
            this.Details.Methods.Delete.CreateInvocation().Execute();
        }
        partial void Delete_CanExecute(ref bool result);
        partial void Delete_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, global::LightSwitchApplication.BugDetail.DetailsClass.PropertySet, global::LightSwitchApplication.BugDetail.DetailsClass.CommandSet, global::LightSwitchApplication.BugDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties.Bug;
                var initializeCommandEntry = global::LightSwitchApplication.BugDetail.DetailsClass.CommandSetProperties.Delete;
                var initializeMethodEntry = global::LightSwitchApplication.BugDetail.DetailsClass.MethodSetProperties.Delete;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Entry
                __BugDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.BugDetail.DetailsClass.__BugDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.BugDetail.DetailsClass.__BugDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.BugDetail.DetailsClass.__BugDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.BugDetail.DetailsClass.__BugDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.BugDetail.DetailsClass.__BugDetail_InvokeCreated,
                    global::LightSwitchApplication.BugDetail.DetailsClass.__BugDetail_InvokeActivated,
                    global::LightSwitchApplication.BugDetail.DetailsClass.__BugDetail_InvokeSaveErrorEvent);
            private static void __BugDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.BugDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.BugDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __BugDetail_InvokeSavingEvent(global::LightSwitchApplication.BugDetail s)
            {
                bool handled = false;
                s.BugDetail_Saving(ref handled);
                return handled;
            }
            private static void __BugDetail_InvokeSavedEvent(global::LightSwitchApplication.BugDetail s)
            {
                s.BugDetail_Saved();
            }
            private static bool __BugDetail_InvokeClosingEvent(global::LightSwitchApplication.BugDetail s)
            {
                bool cancel = false;
                s.BugDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __BugDetail_InvokeCreated(global::LightSwitchApplication.BugDetail s)
            {
                s.BugDetail_Created();
            }
            private static void __BugDetail_InvokeActivated(global::LightSwitchApplication.BugDetail s)
            {
                s.BugDetail_Activated();
            }
            private static bool __BugDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.BugDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.BugDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.BugDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.BugDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.BugDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, global::LightSwitchApplication.Bug>.Data _Bug;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, int>.Data _BugId;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Data _DeleteCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Data _DeleteMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, global::LightSwitchApplication.Bug> Bug
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, global::LightSwitchApplication.Bug>)base.GetItem(global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties.Bug);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, int> BugId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties.BugId);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass> Delete
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.BugDetail.DetailsClass.CommandSetProperties.Delete);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass> Delete
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.BugDetail.DetailsClass.MethodSetProperties.Delete);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, global::LightSwitchApplication.Bug>.Entry
                    Bug = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, global::LightSwitchApplication.Bug>.Entry(
                        "Bug",
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._Bug_Stub,
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._Bug_Validate,
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._Bug_CreateQuery,
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._Bug_OnValueChanged,
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._Bug_OnLoaded);
                private static void _Bug_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BugDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, global::LightSwitchApplication.Bug>.Data> c, global::LightSwitchApplication.BugDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Bug, sf);
                }
                private static void _Bug_Validate(global::LightSwitchApplication.BugDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Bug_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Bug_CreateQuery(global::LightSwitchApplication.BugDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Bug_OnValueChanged(global::LightSwitchApplication.BugDetail s)
                {
                    s.Bug_Changed();
                }

                private static void _Bug_OnLoaded(global::LightSwitchApplication.BugDetail s, bool succeeded)
                {
                    s.Bug_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, int>.Entry
                    BugId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, int>.Entry(
                        "BugId",
                        false,
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._BugId_Stub,
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._BugId_Validate,
                        global::LightSwitchApplication.BugDetail.DetailsClass.PropertySetProperties._BugId_OnValueChanged);
                private static void _BugId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BugDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.BugDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._BugId, sf);
                }
                private static void _BugId_Validate(global::LightSwitchApplication.BugDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.BugId_Validate(r);
                }
                private static void _BugId_OnValueChanged(global::LightSwitchApplication.BugDetail s)
                {
                    s.BugId_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Entry
                    Delete = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Entry(
                        "Delete",
                        global::LightSwitchApplication.BugDetail.DetailsClass.CommandSetProperties._Delete_Stub,
                        global::LightSwitchApplication.BugDetail.DetailsClass.CommandSetProperties._Delete_CreateExecutableObject);
                private static void _Delete_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BugDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Data> c, global::LightSwitchApplication.BugDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._DeleteCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Delete_CreateExecutableObject(global::LightSwitchApplication.BugDetail.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.BugDetail.DetailsClass)d).Methods.Delete.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Entry
                    Delete = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Entry(
                        "Delete",
                        global::LightSwitchApplication.BugDetail.DetailsClass.MethodSetProperties._Delete_Stub,
                        global::LightSwitchApplication.BugDetail.DetailsClass.MethodSetProperties._Delete_CanInvoke,
                        global::LightSwitchApplication.BugDetail.DetailsClass.MethodSetProperties._Delete_InvokeMethod);
                private static void _Delete_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BugDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BugDetail, global::LightSwitchApplication.BugDetail.DetailsClass>.Data> c, global::LightSwitchApplication.BugDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._DeleteMethod, sf);
                }
                private static global::System.Exception _Delete_CanInvoke(global::LightSwitchApplication.BugDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Delete_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Delete_InvokeMethod(global::LightSwitchApplication.BugDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Delete_Execute();
                }

            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class BugsListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private BugsListDetail() : base("LightSwitchApplication:BugsListDetail")
        {
            global::LightSwitchApplication.BugsListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static BugsListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.BugsListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugsListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugsListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugsListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugsListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugsListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugsListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BugsListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Bugs_SelectionChanged();

        partial void Bugs_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bugs_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Bugs visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Bug> Bugs
        {
            get
            {
                return global::LightSwitchApplication.BugsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties.Bugs);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bugs_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass, global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.BugsListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.BugsListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties.Bugs;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass>.Entry
                __BugsListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.BugsListDetail.DetailsClass.__BugsListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.BugsListDetail.DetailsClass.__BugsListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.BugsListDetail.DetailsClass.__BugsListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.BugsListDetail.DetailsClass.__BugsListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.BugsListDetail.DetailsClass.__BugsListDetail_InvokeCreated,
                    global::LightSwitchApplication.BugsListDetail.DetailsClass.__BugsListDetail_InvokeActivated,
                    global::LightSwitchApplication.BugsListDetail.DetailsClass.__BugsListDetail_InvokeSaveErrorEvent);
            private static void __BugsListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.BugsListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.BugsListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __BugsListDetail_InvokeSavingEvent(global::LightSwitchApplication.BugsListDetail s)
            {
                bool handled = false;
                s.BugsListDetail_Saving(ref handled);
                return handled;
            }
            private static void __BugsListDetail_InvokeSavedEvent(global::LightSwitchApplication.BugsListDetail s)
            {
                s.BugsListDetail_Saved();
            }
            private static bool __BugsListDetail_InvokeClosingEvent(global::LightSwitchApplication.BugsListDetail s)
            {
                bool cancel = false;
                s.BugsListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __BugsListDetail_InvokeCreated(global::LightSwitchApplication.BugsListDetail s)
            {
                s.BugsListDetail_Created();
            }
            private static void __BugsListDetail_InvokeActivated(global::LightSwitchApplication.BugsListDetail s)
            {
                s.BugsListDetail_Activated();
            }
            private static bool __BugsListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.BugsListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.BugsListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.BugsListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.BugsListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable BugsQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.ApplicationData.Bugs,
                    "Tester");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass, global::LightSwitchApplication.Bug>.Data _Bugs;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass, global::LightSwitchApplication.Bug> Bugs
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass, global::LightSwitchApplication.Bug>)base.GetItem(global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties.Bugs);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass, global::LightSwitchApplication.Bug>.Entry
                    Bugs = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass, global::LightSwitchApplication.Bug>.Entry(
                        "Bugs",
                        global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties._Bugs_Stub,
                        global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties._Bugs_Validate,
                        global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties._Bugs_CreateQuery,
                        global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties._Bugs_SelectionChanged,
                        global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties._Bugs_OnCollectionChanged,
                        global::LightSwitchApplication.BugsListDetail.DetailsClass.PropertySetProperties._Bugs_OnLoaded);
                private static void _Bugs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BugsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.BugsListDetail, global::LightSwitchApplication.BugsListDetail.DetailsClass, global::LightSwitchApplication.Bug>.Data> c, global::LightSwitchApplication.BugsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Bugs, sf);
                }
                private static void _Bugs_Validate(global::LightSwitchApplication.BugsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Bugs_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Bugs_CreateQuery(global::LightSwitchApplication.BugsListDetail.DetailsClass d, object[] args)
                {
                    return d.BugsQuery();
                }
                private static void _Bugs_SelectionChanged(global::LightSwitchApplication.BugsListDetail s)
                {
                    s.Bugs_SelectionChanged();
                }
                private static void _Bugs_OnCollectionChanged(global::LightSwitchApplication.BugsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Bugs_Changed(e);
                }
                private static void _Bugs_OnLoaded(global::LightSwitchApplication.BugsListDetail s, bool succeeded)
                {
                    s.Bugs_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
