

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Bug : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Bug entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Bug()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Bug(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Bug> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Bug.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bug_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bug_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Summary
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Summary);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Summary, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Detail
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Detail);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Detail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Page
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Page);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Page, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Page_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Page_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Page_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string StepsToReproduce
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.StepsToReproduce);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.StepsToReproduce, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StepsToReproduce_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StepsToReproduce_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StepsToReproduce_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateLogged
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.DateLogged);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.DateLogged, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateLogged_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateLogged_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateLogged_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Status
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Status);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Status, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] Image
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Image);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Image, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Image_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Image_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Image_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Tester Tester
        {
            get
            {
                return global::LightSwitchApplication.Bug.DetailsClass.GetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Tester);
            }
            set
            {
                global::LightSwitchApplication.Bug.DetailsClass.SetValue(this, global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Tester, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tester_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tester_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Tester_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Bug,
                global::LightSwitchApplication.Bug.DetailsClass,
                global::LightSwitchApplication.Bug.DetailsClass.IImplementation,
                global::LightSwitchApplication.Bug.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass>.Entry
                __BugEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass>.Entry(
                    global::LightSwitchApplication.Bug.DetailsClass.__Bug_CreateNew,
                    global::LightSwitchApplication.Bug.DetailsClass.__Bug_Created,
                    global::LightSwitchApplication.Bug.DetailsClass.__Bug_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Bug __Bug_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Bug> es)
            {
                return new global::LightSwitchApplication.Bug(es);
            }
            private static void __Bug_Created(global::LightSwitchApplication.Bug e)
            {
                e.Bug_Created();
            }
            private static bool __Bug_AllowSaveWithErrors(global::LightSwitchApplication.Bug e)
            {
                bool result = false;
                e.Bug_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Bug.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string> Summary
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Summary) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string> Detail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Detail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string> Page
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Page) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string> StepsToReproduce
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.StepsToReproduce) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::System.DateTime> DateLogged
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.DateLogged) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string> Status
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Status) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]> Image
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Image) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::LightSwitchApplication.Tester> Tester
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Tester) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::LightSwitchApplication.Tester>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Summary { get; set; }
                new string Detail { get; set; }
                new string Page { get; set; }
                new string StepsToReproduce { get; set; }
                new global::System.DateTime DateLogged { get; set; }
                new string Status { get; set; }
                new byte[] Image { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Tester { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, int>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry
                    Summary = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry(
                        "Summary",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Summary_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Summary_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Summary_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Summary_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Summary_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Summary_OnValueChanged);
                private static void _Summary_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._Summary, sf);
                }
                private static bool _Summary_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.Summary_IsReadOnly(ref result);
                    return result;
                }
                private static void _Summary_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Summary_Validate(r);
                }
                private static string _Summary_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.Summary;
                }
                private static void _Summary_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Summary = v;
                }
                private static void _Summary_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.Summary_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry
                    Detail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry(
                        "Detail",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Detail_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Detail_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Detail_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Detail_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Detail_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Detail_OnValueChanged);
                private static void _Detail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._Detail, sf);
                }
                private static bool _Detail_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.Detail_IsReadOnly(ref result);
                    return result;
                }
                private static void _Detail_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Detail_Validate(r);
                }
                private static string _Detail_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.Detail;
                }
                private static void _Detail_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Detail = v;
                }
                private static void _Detail_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.Detail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry
                    Page = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry(
                        "Page",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Page_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Page_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Page_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Page_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Page_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Page_OnValueChanged);
                private static void _Page_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._Page, sf);
                }
                private static bool _Page_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.Page_IsReadOnly(ref result);
                    return result;
                }
                private static void _Page_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Page_Validate(r);
                }
                private static string _Page_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.Page;
                }
                private static void _Page_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Page = v;
                }
                private static void _Page_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.Page_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry
                    StepsToReproduce = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry(
                        "StepsToReproduce",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._StepsToReproduce_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._StepsToReproduce_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._StepsToReproduce_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._StepsToReproduce_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._StepsToReproduce_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._StepsToReproduce_OnValueChanged);
                private static void _StepsToReproduce_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._StepsToReproduce, sf);
                }
                private static bool _StepsToReproduce_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.StepsToReproduce_IsReadOnly(ref result);
                    return result;
                }
                private static void _StepsToReproduce_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StepsToReproduce_Validate(r);
                }
                private static string _StepsToReproduce_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.StepsToReproduce;
                }
                private static void _StepsToReproduce_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, string v)
                {
                    d.ImplementationEntity.StepsToReproduce = v;
                }
                private static void _StepsToReproduce_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.StepsToReproduce_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::System.DateTime>.Entry
                    DateLogged = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::System.DateTime>.Entry(
                        "DateLogged",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._DateLogged_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._DateLogged_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._DateLogged_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._DateLogged_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._DateLogged_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._DateLogged_OnValueChanged);
                private static void _DateLogged_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._DateLogged, sf);
                }
                private static bool _DateLogged_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.DateLogged_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateLogged_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateLogged_Validate(r);
                }
                private static global::System.DateTime _DateLogged_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.DateLogged;
                }
                private static void _DateLogged_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateLogged = global::LightSwitchApplication.Bug.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DateLogged_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.DateLogged_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry
                    Status = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Entry(
                        "Status",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Status_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Status_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Status_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Status_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Status_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Status_OnValueChanged);
                private static void _Status_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._Status, sf);
                }
                private static bool _Status_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.Status_IsReadOnly(ref result);
                    return result;
                }
                private static void _Status_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Status_Validate(r);
                }
                private static string _Status_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.Status;
                }
                private static void _Status_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Status = v;
                }
                private static void _Status_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.Status_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Entry
                    Image = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Entry(
                        "Image",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Image_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Image_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Image_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Image_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Image_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Image_OnValueChanged);
                private static void _Image_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._Image, sf);
                }
                private static bool _Image_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.Image_IsReadOnly(ref result);
                    return result;
                }
                private static void _Image_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Image_Validate(r);
                }
                private static byte[] _Image_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.Image;
                }
                private static void _Image_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.Image = v;
                }
                private static void _Image_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.Image_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::LightSwitchApplication.Tester>.Entry
                    Tester = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::LightSwitchApplication.Tester>.Entry(
                        "Tester",
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_Stub,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_ComputeIsReadOnly,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_Validate,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_GetCoreImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_GetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_SetImplementationValue,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_Refresh,
                        global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties._Tester_OnValueChanged);
                private static void _Tester_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Bug.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::LightSwitchApplication.Tester>.Data> c, global::LightSwitchApplication.Bug.DetailsClass d, object sf)
                {
                    c(d, ref d._Tester, sf);
                }
                private static bool _Tester_ComputeIsReadOnly(global::LightSwitchApplication.Bug e)
                {
                    bool result = false;
                    e.Tester_IsReadOnly(ref result);
                    return result;
                }
                private static void _Tester_Validate(global::LightSwitchApplication.Bug e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Tester_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Tester_GetCoreImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.ImplementationEntity.Tester;
                }
                private static global::LightSwitchApplication.Tester _Tester_GetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Tester, global::LightSwitchApplication.Tester.DetailsClass>(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Tester, ref d._Tester);
                }
                private static void _Tester_SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass d, global::LightSwitchApplication.Tester v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Tester, ref d._Tester, (i, ev) => i.Tester = ev, v);
                }
                private static void _Tester_Refresh(global::LightSwitchApplication.Bug.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Bug.DetailsClass.PropertySetProperties.Tester, ref d._Tester);
                }
                private static void _Tester_OnValueChanged(global::LightSwitchApplication.Bug e)
                {
                    e.Tester_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data _Summary;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data _Detail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data _Page;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data _StepsToReproduce;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::System.DateTime>.Data _DateLogged;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, string>.Data _Status;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, byte[]>.Data _Image;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Bug, global::LightSwitchApplication.Bug.DetailsClass, global::LightSwitchApplication.Tester>.Data _Tester;
            
        }
    
        #endregion
    }
    
    #endregion
}
